

export const FETCH_HOME_LIST = 'FETCH_HOME_LIST';
export const RECEIVE_HOME_LIST = 'RECEIVE_HOME_LIST';

export const FETCH_CLASS_LIST = 'FETCH_CLASS_LIST';
export const RECEIVE_CLASS_LIST = 'RECEIVE_CLASS_LIST';

export const FETCH_CLASS_DETAIL_LIST = 'FETCH_CLASS_DETAIL_LIST';
export const RECEIVE_CLASS_DETAIL_LIST = 'RECEIVE_CLASS_DETAIL_LIST';
export const RESET_DETAIL_LIST = 'RESET_DETAIL_LIST';
